spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test_pigs?serverTimeZone=UTC&useSSL=true
          username: pigs
          password: "@pigs$deads"
        test:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test_pigs?serverTimeZone=UTC&useSSL=true
          username: pigs
          password: "@pigs$deads"